---
- hosts: localhost
  connection: localhost
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - fzf

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /root/.bashrc
     owner: root
     group: root

  - name: copy .fzf.bash file
    copy:
     src: files/fzf.bash
     dest: /root/.fzf.bash
     owner: root
     group: root

   - name: Clone fzf
     git:
       repo: https://github.com/junegunn/fzf.git
       dest: /root/~.fzf
       depth: 1
       clone: yes
       update: yes
