---
- hosts: localhost
  connection: localhost
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - fzf

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /root/.bashrc
     owner: root
     group: root

  - name: clone fzf
    git:
     repo: https://github.com/junegunn/fzf.git
     dest: /root/.fzf
     clone: yes
     depth: 1
     update: yes
